version: "3"

services:
  loki:
    image: grafana/loki:2.6.1
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    depends_on:
      - promtail

  promtail:
    image: grafana/promtail:2.6.1
    volumes:
      - ./logs:/logs
      - ./data/nginx/log:/nginx/log
      - ./promtail/config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    ports:
      - 9080:9080

  grafana:
    build:
      context: grafana/
      args:
        GRAFANA_VERSION: latest
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    user: "$UID:$GID"
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./data/grafana:/var/lib/grafana
    ports:
      - "3001:3000"
    depends_on:
      - loki
      - promtail
