datasources:
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: true
    version: 1
    editable: false
    apiVersion: 1
  - name: Redis
    type: redis-datasource
    access: proxy
    isDefault: false
    orgId: 1
    version: 1
    url: redis://host.docker.internal:6379
    jsonData:
      poolSize: 5
      timeout: 10
      pingInterval: 0
      pipelineWindow: 0
    editable: true